services:
  elomind_web:
    build:
      context: ../elomind-web
    container_name: elomind_web
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ../elomind-web:/app
    command: sh -c "npm install --legacy-peer-deps --verbose && npm run dev"

  api:
    build:
      context: ../elomind-api
      dockerfile: server/Dockerfile
    container_name: elomind_api
    working_dir: /var/www
    volumes:
      - ../elomind-api:/var/www
    expose:
      - 9000
    depends_on:
      - elomind_db
    networks:
      - elomind_network

  nginx:
    image: nginx:1.25-alpine
    container_name: elomind_nginx
    ports:
      - 8080:80
    volumes:
      - ../elomind-api/server:/var/www
      - ../elomind-api/server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - elomind_network

  elomind_db:
    image: mysql:8.0
    container_name: elomind_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elomind
      MYSQL_USER: elomind
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - elomind_network

volumes:
  db_data:

networks:
  elomind_network:
    name: elomind_network
